name: "shannu-first-action"

on:
  push:
    branches: 
      - main 

jobs: 
  terraform-job:  
    runs-on: shannu  # Make sure your self-hosted runner is online and tagged correctly
    environment: prod 


    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./todoapp_infra 
        
      - name: Terraform Fmt Check
        run: terraform fmt
        working-directory: ./todoapp_infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./todoapp_infra

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Plan
        run: terraform plan 
        working-directory: ./todoapp_infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./todoapp_infra

     
    


      
     
    
     
