name: "shannu-first-action"

on:
  push:
    branches:
      - main

jobs:
  terraform-job:
    runs-on: shannu   # self-hosted runner label
    environment: prod

    permissions:
      id-token: write   # required for OIDC
      contents: read    # required to checkout code

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Install unzip (required to extract Terraform)
        run: sudo apt-get update && sudo apt-get install -y unzip curl

      - name: Install Terraform manually
        run: |
          TERRAFORM_VERSION=1.13.0
          curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Terraform Init
        run: terraform init
        working-directory: ./todoapp_infra

      - name: Terraform Fmt Check
        run: terraform fmt
        working-directory: ./todoapp_infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./todoapp_infra

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login (Federated Identity)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: terraform Plan
        run: terraform plan
        working-directory: ./todoapp_infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./todoapp_infra
