name: "shannu-first-action"

on:
  push:
    branches:
      - main 

jobs:
  terraform-job:
    runs-on: shannu   # self-hosted runner
    environment: prod

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl
          TERRAFORM_VERSION=1.13.0
          curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login (OIDC) 
        uses: azure/login@v2
        with:
          client-id: 21cf03ac-6297-41a8-9ba2-77d69ac33150
          tenant-id: e4cbbb94-337a-466a-a645-8f7815ae9ae3
          subscription-id: 541aa6e9-5e65-4ca7-bd4b-befb88d6f6ae

      - name: Terraform Init
        run: terraform init
        working-directory: ./todoapp_infra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./todoapp_infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./todoapp_infra
